name: golangci-lint

on: [pull_request]

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: src/github.com/aws/amazon-ecs-agent
      - name: GO_VERSION
        run: |
          cd $GITHUB_WORKSPACE/src/github.com/aws/amazon-ecs-agent
          echo "GO_VERSION=$(cat GO_VERSION)" >> $GITHUB_ENV
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42.1
          args: -v
          skip-go-installation: true
          only-new-issues: true